### ISSUE TITLE
Final group capstone: set up your Kanban board

### ISSUE THREAD

**Issue by lojacho** [gjuliao/car_app_backend#19]
In this pull request, We were able to: 

Set up a [kanban board](https://github.com/users/gjuliao/projects/2/views/1) to manage our project tasks: By organizing our tasks into different stages and columns, we can better visualize our progress and plan our next steps more effectively.

Created a project to manage the entire scope of the project: By having a centralized location for our project files and documentation, we can ensure that everyone is on the same page and that nothing falls through the cracks.

Created two separate repositories for [front-end](https://github.com/gjuliao/car_app_frontend) and [back-end](https://github.com/gjuliao/car_app_backend) development: By separating our code into two distinct repositories, we can better manage changes, dependencies, and version control.

Created issues and assigned them to the appropriate repositories: By breaking down our tasks into smaller, more manageable chunks and assigning them to specific team members, we can ensure that everyone is working on the right things at the right time.

Thanks for the review.
We are a group of 5
![kanbanboard](https://user-images.githubusercontent.com/94698411/235999755-6752d595-6f2a-4975-a368-14cc0da8b199.jpg)

**Comment by Meltrust** [comment]
Hi @dgcuenca,

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!



### To highlight:

- All tasks have been assigned✔️ 

![You can do it](https://media.giphy.com/media/FemTGpEZeK27M5fKL4/giphy.gif)

## Required Changes ♻️

According to the [project requirements](https://github.com/microverseinc/curriculum-final-capstone/blob/main/projects/setup_kanban_board.md):

![image](https://user-images.githubusercontent.com/57421823/235993509-cd156f09-d5bd-4921-a93f-43562c690332.png)

At the time of this review, however, these are the pointings:

@paulsaenzsucre 44
@Juank628 46
@gjuliao 46
@dgcuenca 32
@belaymit 6

The general rule is that nobody can have more than 5 points than any other team member.  That includes the whole team.

As you can see, @dgcuenca has 32 points, which is a lot less than @gjuliao who has 46.  Also, @belaymit has just 6 points.

Therefore:

- [x] Kindly, make sure no one in your team has more than 5 points than any other member.  

That way, we will meet this particular requirement. 💪 

_Tip:  You could reassign tasks, move the numbers, change the values._


- [x] This task does not have any points:

![image](https://user-images.githubusercontent.com/57421823/236000441-d8cc3d23-b37a-424d-9c4d-fa3a83d7bcd2.png)

Kindly add points to it.  While on it, kindly remember that no team member may have more than 5 points than any other. 👍 






## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Juank628** [comment]
Thanks for your comments!
Changes were done

**Comment by Meltrust** [comment]
_note: I tried to contact the student to offer help, but got no response this time._

Hi @dgcuenca,

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

![You can do it](https://media.giphy.com/media/FemTGpEZeK27M5fKL4/giphy.gif)

 ## Required Changes ♻️

- [x] At the time of this re-review, the pointings are as follows:

paulsaenzsucre 44
Juank628 46
gjuliao 46
dgcuenca 29
belaymit 21

Again, @dgcuenca and @belaymit have very few points compared to @Juank628, @gjuliao, and @paulsaenzsucre.   

The rule is that nobody can have more than 5 points than any other person on the team.

This means that @dgcuenca and @belaymit should have 41-49 points in order to meet the rule.

If I'm not being clear enough, kindly read the [project requirements](https://github.com/microverseinc/curriculum-final-capstone/blob/main/projects/setup_kanban_board.md).

If you need extra help/clarification, kindly bug me on Slack and I'll be happy to help.  👍 

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by lojacho** [comment]
Hello @Meltrust 

Thanks for the review, changes were implemented.

**Comment by Meltrust** [comment]
Hi @dgcuenca,


## Wow, you did it 🎉
![Brilliant](https://media.giphy.com/media/d31w24psGYeekCZy/giphy.gif)
## Thank you for implementing the changes requested by the previous reviewer 💪 🥇 ㊗️ 
### Well done!




Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

### To highlight

- Student pointing are now equal, and all tasks have points.✔️ 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
